### ISSUE TITLE
Create base client/server Rust projects

### ISSUE THREAD

**Issue by vkatsuba** [oda-components/oda-api-sdk-rust#4]
## `oda-api-sdk-rust` version
[latest](https://github.com/oda-components/oda-api-sdk-rust/releases)

## `OS` version
**All**

## Description
* **Motivation**
In Rust SDK should be implemented client/server projects.
* **Proposal**
Create base client/server projects over `cargo`:
```
$ cargo new client
$ cargo new server
```

## Current behavior
Missed client/server projects.

## Expected behavior
The client/server projects are added.

## Config
Default configuration which implemented by `cargo`.

**Comment by vances** [comment]
Wrong project.  We already have client/server subdirectories for SDK here.  The RI is where we need this.
