### ISSUE TITLE
Rename current CI to POW

### ISSUE THREAD

**Issue by vkatsuba** [oda-components/oda-api-sdk-rust#5]
## `oda-api-sdk-rust` version
[latest](https://github.com/oda-components/oda-api-sdk-rust/releases)

## `OS` version
**All**

## Description
* **Motivation**
Current project expect sub folders with Rust code base. This code base should be covered by tests and those tests check should be added into CI. Currently existing CI has wrong names - because it actually provide a demo of POW(Prof Of Work) of build Rust SDK over Open API generator. It make sense rename CI to POW.
* **Proposal**
Rename existing CI to POW.

## Current behavior
The CI has wrong names which can confuse, because current CI provide POW - not a source code of project.

## Expected behavior
The CI for POW has correct names.

## Config
`N/A`

**Comment by vances** [comment]
We don't need a POW, we do need a CI.  When we are ready the CI will build the SDK and publish crates.
